### ISSUE TITLE
Hey guys, the 'PersonalInfo' form must  add "one and only one" record; which then can be updated or deleted. In that case, would it be okay if I remove the ListView from my form? Thanks!

### ISSUE THREAD

**Issue by PabloParamo** [Tafe18S202/Tafe18S202#2]

**Comment by 000316926** [comment]
Hi Pablo, you should be able to remove the list since it's only one record.

**Comment by PabloParamo** [comment]
Thanks Chris!

**Comment by PabloParamo** [comment]
After exploring many different options to be able to modify the "only" record and yet being able to display it when the form is open, I came to the conclusion that it would be best to keep the ListView as it was. That is currently the easiest way I can achieve the "Add" (only one record), Modify and Delete as per required by the client. The form is now completely functioning - only one record can be added to the List.
Please let me know if this is okay with you guys - or whether you may have a different approach that can be implemented within our timeframe :)

**Comment by PabloParamo** [comment]
Forgot to mention, that the ListView will keep only one record :)
