### ISSUE TITLE
Visual Studio Issue (Build Project to update Design View)

### ISSUE THREAD

**Issue by BlaqkFyre** [Tafe18S202/Tafe18S202#4]
I was able to easily clone and branch my feature at home and begin work on it, but am now faced with the .xaml files giving me an error/bug of

'**Build the Project to update Design view.**
_The Design view cannot display correctly because some custom elements have not yet been built._'

This can be worked around by closing an re-opening the file every time it happens, but this issue doesn't happen at TAFE. I have cleaned, rebuilt, built but it always happens. Not sure why. Any help would be appreciated. Thanks.

**Comment by PabloParamo** [comment]
Hi Luke, I just came across your post. I haven't had that issue with the project so far. The project runs fine both at TAFE and home PCs. I'll be happy to see if I can help when we meet this afternoon. But in the meantime this [link could be of some help](https://blogs.msdn.microsoft.com/wsdevsol/2012/10/31/why-does-the-xaml-designer-report-that-my-custom-elements-have-not-been-built/). 
Cheers!

**Comment by Reznal** [comment]
After having a look into this, I have come across [this] (https://programmingstuff2016.wordpress.com/2016/09/17/build-the-project-to-update-design-view/) which resolves the issue by cleaing the  Xaml Design Shadow Cache.

> Process:
> 
> Right-Click on the solution in the Solution Explorer and Choose “Clean Solution”
> Shutdown Visual Studio
> Delete the ShadowCache folder
> Reopened the Visual Studio project
> Rebuild the solution
